#!/bin/bash

read -p "Sisesta ridade arv: " rows
read -p "Sisesta tarnide arv reas: " cols

for ((i=1; i<=$rows; i++)); do
    for ((j=1; j<=$cols; j++)); do
        echo -n "* "
    done
    echo
done


