#!/bin/bash

# Küsime kasutajalt kuu numbrit
echo -n "Sisesta kuu number: "
read kuu

# Kontrollime kuu numbrit ja vastavalt sellele määrame aastaaja
# Kasutame case-lause struktuuri, et leida vastavus kuu numbrile
case "$kuu" in
    12|1|2)
        echo "Praegu on talv";;
    3|4|5)
        echo "Praegu on kevad";;
    6|7|8)
        echo "Praegu on suvi";;
    9|10|11)
        echo "Praegu on sügis";;
    *)
        echo "Vigane kuu number! Sisesta kuu number vahemikus 1 kuni 12.";;
esac

